# importing libraries
import numpy as np
import pandas as pd 
from gensim.models import Word2Vec # metin temsili için
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import SimpleRNN,Dense,Embedding
from keras.preprocessing.text import Tokenizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
# creating dataset
dataset = [
    {"text": "Ürün çok hızlı kargolandı, çok memnun kaldım!", "label": "positive"},
    {"text": "Siparişim eksik geldi, müşteri hizmetleri ilgilenmedi.", "label": "negative"},
    {"text": "Web sitesi çok kullanışlı, alışveriş yaparken hiç zorlanmadım.", "label": "positive"},
    {"text": "Ürün açıklaması yanıltıcıydı, beklediğim gibi çıkmadı.", "label": "negative"},
    {"text": "İndirimler gerçekten harika, fiyatlar çok uygun!", "label": "positive"},
    {"text": "Ürün kırık geldi ve iade süreci çok uğraştırıcıydı.", "label": "negative"},
    {"text": "Müşteri hizmetleri çok ilgili, hemen yardımcı oldular.", "label": "positive"},
    {"text": "Sipariş verdim ama hala kargoya verilmedi.", "label": "negative"},
    {"text": "Canlı destek ekibi çok hızlı dönüş yapıyor, teşekkürler!", "label": "positive"},
    {"text": "Stokta var görünen ürünü sipariş ettim ama iptal edildi.", "label": "negative"},
    {"text": "Ürün tam beklediğim gibi geldi, paketleme de çok özenliydi.", "label": "positive"},
    {"text": "Fiyatlar çok pahalı ve kampanyalar yanıltıcı.", "label": "negative"},
    {"text": "Hediye paketi seçeneği olması çok güzel, arkadaşım çok sevindi!", "label": "positive"},
    {"text": "Kargo firması ürünü yanlış adrese teslim etti, uğraştırdı.", "label": "negative"},
    {"text": "Üyelik süreci çok basit ve güvenilir görünüyor.", "label": "positive"},
    {"text": "Ödeme ekranında sürekli hata alıyorum, alışveriş yapamıyorum.", "label": "negative"},
    {"text": "Mobil uygulaması çok pratik ve kullanışlı!", "label": "positive"},
    {"text": "Kargo takibi sürekli güncellenmiyor, bilgi alamıyorum.", "label": "negative"},
    {"text": "Ürünlerin yorumlarına bakarak güvenle alışveriş yapabiliyorum.", "label": "positive"},
    {"text": "Satıcı sorularıma cevap vermedi, destek sıfır.", "label": "negative"},
    {"text": "Kampanya dönemlerinde fiyatlar gerçekten düşüyor, harika!", "label": "positive"},
    {"text": "Sepete eklediğim ürün stokta yok diye sonradan iptal edildi.", "label": "negative"},
    {"text": "İade süreci çok kolay ve hızlı, hiç zorlanmadım.", "label": "positive"},
    {"text": "Kargo ücreti çok yüksek, bu yüzden alışveriş yapmadım.", "label": "negative"},
    {"text": "Site arayüzü çok modern ve alışverişi kolaylaştırıyor.", "label": "positive"},
    {"text": "Ürün açıklamalarında yanlış bilgi verilmiş, kandırıldım.", "label": "negative"},
    {"text": "Satıcı çok ilgiliydi, sorularımı hemen yanıtladı.", "label": "positive"},
    {"text": "İndirim kuponu kullanmaya çalıştım ama geçerli olmadı.", "label": "negative"},
    {"text": "Paketleme çok sağlamdı, ürün hasarsız ulaştı.", "label": "positive"},
    {"text": "Kargom 2 hafta geçti hala gelmedi, çok kötü hizmet.", "label": "negative"},
    {"text": "Ürün resimdeki gibi geldi, hiçbir fark yok!", "label": "positive"},
    {"text": "Müşteri hizmetleri çok yavaş, saatlerce bekledim.", "label": "negative"},
    {"text": "Ücretsiz kargo seçeneği olması çok avantajlı!", "label": "positive"},
    {"text": "Siparişimin durumu hakkında bilgi alamıyorum.", "label": "negative"},
    {"text": "Ürünlerin çeşitliliği çok fazla, her şeyi bulabiliyorum!", "label": "positive"},
    {"text": "İade ettiğim ürünün parasını hala geri alamadım.", "label": "negative"},
    {"text": "Kampanyalar çok avantajlı, sürekli takip ediyorum.", "label": "positive"},
    {"text": "Satıcı ürünü yanlış yolladı, değiştirmekle uğraştım.", "label": "negative"},
    {"text": "Alışveriş deneyimim çok iyiydi, herkese öneririm!", "label": "positive"},
    {"text": "Kredi kartıyla ödeme yaparken sürekli hata aldım.", "label": "negative"},
    {"text": "Ürün yorumları çok açıklayıcı, alırken fikir veriyor.", "label": "positive"},
    {"text": "Destek ekibiyle iletişime geçmek çok zor.", "label": "negative"},
    {"text": "Teslimat çok hızlı oldu, ertesi gün elime ulaştı!", "label": "positive"},
    {"text": "Aldığım ürün defolu çıktı ve satıcı ilgilenmedi.", "label": "negative"},
    {"text": "Güvenilir bir site, ödeme sırasında hiç sorun yaşamadım.", "label": "positive"},
    {"text": "Bana yanlış ürün gönderdiler, iade süreci çok uzun sürdü.", "label": "negative"},
    {"text": "Siteye her girişimde yeni kampanyalarla karşılaşıyorum, harika!", "label": "positive"},
    {"text": "Ürün elime çok geç ulaştı, beklediğimden uzun sürdü.", "label": "negative"},
    {"text": "Satıcı çok nazik ve hızlı bir şekilde kargoladı, teşekkür ederim!", "label": "positive"},
   {"text": "Ürün beklediğimden daha kaliteli çıktı, çok memnunum.", "label": "positive"},
   {"text": "Sipariş iptal edildi ama para iadesi hala yapılmadı!", "label": "negative"},
   {"text": "Fiyat-performans açısından çok iyi bir ürün, tavsiye ederim.", "label": "positive"},
   {"text": "Müşteri hizmetlerine ulaşmak imkansız, telefonları açmıyorlar.", "label": "negative"},
   {"text": "İndirim günlerinde alışveriş yapmak çok avantajlı oluyor.", "label": "positive"},
   {"text": "Kargom başka bir adrese teslim edilmiş, ulaşmakta zorlandım.", "label": "negative"},
   {"text": "Ürün paketlemesi çok özenliydi, hiç zarar görmemişti.", "label": "positive"},
   {"text": "Alışveriş sepetim sürekli sıfırlanıyor, site çok kötü çalışıyor.", "label": "negative"},
   {"text": "Satıcı anında cevap verdi ve yardımcı oldu, çok memnun kaldım.", "label": "positive"},
   {"text": "Beden tablosu yanlış verilmiş, kıyafet üzerime olmadı.", "label": "negative"},
   {"text": "Aldığım telefon tam istediğim gibi, kutusu bile zarar görmemişti.", "label": "positive"},
   {"text": "Kargo ücretleri gereksiz derecede pahalı, almaktan vazgeçtim.", "label": "negative"},
   {"text": "Fiyatlar piyasaya göre uygun ve kampanyalar çok iyi.", "label": "positive"},
   {"text": "Ürünün rengi farklı geldi, görsellerde yanıltıcı gösterilmiş.", "label": "negative"},
   {"text": "Ödeme seçenekleri çok fazla, rahatça alışveriş yapabiliyorum.", "label": "positive"},
   {"text": "Kargomda eksik ürün vardı, satıcı ilgilenmedi.", "label": "negative"},
   {"text": "Canlı destek ekibi dakikalar içinde yardımcı oldu, çok iyiler!", "label": "positive"},
   {"text": "Aynı gün kargo yazıyordu ama 5 gün geçti hala gelmedi.", "label": "negative"},
   {"text": "Ürünlerin açıklamaları detaylı ve net, karar vermek çok kolay.", "label": "positive"},
   {"text": "Ödeme sırasında hata aldım ve destek ekibi hiç yardımcı olmadı.", "label": "negative"},
   {"text": "Bu kadar kaliteli bir ürün beklemiyordum, gerçekten şaşırdım.", "label": "positive"},
   {"text": "Alışveriş yapmak çok kolay ama iade süreci çok karışık.", "label": "negative"},
   {"text": "Kampanyalar çok avantajlı ve fırsatlar sürekli güncelleniyor.", "label": "positive"},
   {"text": "Teslimat süresi çok uzun, siparişim 10 günde geldi.", "label": "negative"},
   {"text": "Web sitesi arayüzü modern ve kullanımı çok rahat.", "label": "positive"},
   {"text": "İade kodu almam gerekiyordu ama sistem hata veriyor.", "label": "negative"},
   {"text": "Ürünü hediye olarak aldım, paketleme çok şıktı.", "label": "positive"},
   {"text": "Maalesef satıcıya ulaşamıyorum, siparişimi değiştirmek istiyorum.", "label": "negative"},
   {"text": "Güvenilir bir alışveriş sitesi, gönül rahatlığıyla sipariş verdim.", "label": "positive"},
   {"text": "Aynı ürünü başka sitede daha ucuza gördüm, fiyatlar şişirilmiş.", "label": "negative"},
   {"text": "Kuponlarla alışveriş yapmak çok keyifli ve indirimler güzel.", "label": "positive"},
   {"text": "Kargo paketim yırtık geldi, içindeki ürün hasar görmüştü.", "label": "negative"},
   {"text": "Ürünü sipariş ettim, beklediğimden çok daha hızlı geldi.", "label": "positive"},
   {"text": "Sepetime eklediğim ürün stokta yokmuş, siparişim iptal edildi.", "label": "negative"},
   {"text": "Alışveriş deneyimim çok güzeldi, kesinlikle tekrar sipariş vereceğim.", "label": "positive"},
   {"text": "Yorumlara güvenerek aldım ama ürün hayal kırıklığı oldu.", "label": "negative"},
   {"text": "Satıcı çok ilgiliydi, her soruma hemen cevap verdi.", "label": "positive"},
   {"text": "Siparişimde yanlış ürün geldi, değiştirmek için çok uğraştım.", "label": "negative"},
   {"text": "Ürün fotoğraflardaki gibi, hiçbir fark yok.", "label": "positive"},
   {"text": "Kargo takip numarası yanlış verildi, paketimi takip edemedim.", "label": "negative"},
   {"text": "Ürün açıklamasında yazan her şey birebir doğruydu.", "label": "positive"},
   {"text": "İndirimler harika ama stoklar hemen tükeniyor.", "label": "positive"},
   {"text": "Satıcıyla iletişim kuramıyorum, siparişim hakkında bilgi almak istiyorum.", "label": "negative"},
   {"text": "Ücretsiz kargo fırsatları çok güzel, ekstra masraf olmuyor.", "label": "positive"},
   {"text": "İndirim kodu çalışmadı, sistem hata verdi.", "label": "negative"},
   {"text": "Ürünün kalitesi beklediğimden çok daha iyi, bayıldım!", "label": "positive"},
   {"text": "Siparişim sorunsuz ve eksiksiz geldi, çok memnun kaldım.", "label": "positive"},
   {"text": "Ürün beklediğim gibi değildi, kalitesi çok düşük.", "label": "negative"},
   {"text": "Kargo çok hızlı geldi, ertesi gün elimdeydi!", "label": "positive"},
   {"text": "Müşteri hizmetleri çok ilgisiz, sorunumu çözmediler.", "label": "negative"},
   {"text": "Ürün harika paketlenmişti, hasarsız ulaştı.", "label": "positive"},
   {"text": "Siparişim yanlış adrese teslim edildi, çok uğraştırdı.", "label": "negative"},
   {"text": "İndirim fırsatları gerçekten çok avantajlı!", "label": "positive"},
   {"text": "Aldığım ürün stokta yokmuş, iptal ettiler.", "label": "negative"},
   {"text": "Web sitesi çok kullanışlı, kolayca alışveriş yapabiliyorum.", "label": "positive"},
   {"text": "Kargo takip sistemi düzgün çalışmıyor, bilgi alamıyorum.", "label": "negative"},
   {"text": "Satıcı çok ilgiliydi, hemen geri dönüş yaptı.", "label": "positive"},
   {"text": "Ödeme sırasında sürekli hata alıyorum, alışveriş yapamıyorum.", "label": "negative"},
   {"text": "Ürün tam beklediğim gibi geldi, fiyatına göre çok iyi.", "label": "positive"},
   {"text": "Kargo çok gecikti, 2 hafta oldu hala gelmedi.", "label": "negative"},
   {"text": "Ürün açıklamaları çok detaylı ve bilgilendirici.", "label": "positive"},
   {"text": "İade süreci çok zor ve uzun sürüyor.", "label": "negative"},
   {"text": "Ücretsiz kargo seçeneği olması çok avantajlı!", "label": "positive"},
   {"text": "Ürün resimde göründüğünden farklı geldi, hayal kırıklığına uğradım.", "label": "negative"},
   {"text": "Kampanya dönemlerinde fiyatlar gerçekten çok uygun.", "label": "positive"},
   {"text": "Müşteri hizmetlerine ulaşmak imkansız!", "label": "negative"},
   {"text": "Paketleme çok özenliydi, hasar almadan teslim edildi.", "label": "positive"},
   {"text": "Ürün açıklamasında yazan bilgiler doğru değildi.", "label": "negative"},
   {"text": "Satıcı sorularımı hızlıca yanıtladı, güvenilir bir alışveriş deneyimi oldu.", "label": "positive"},
   {"text": "İade ettiğim ürünün parasını hala alamadım.", "label": "negative"},
   {"text": "Kargo tahminimden daha erken geldi, harika!", "label": "positive"},
   {"text": "Ürünün fiyatı çok pahalı, indirim yapmaları gerekiyor.", "label": "negative"},
   {"text": "Canlı destek ekibi çok hızlı ve yardımcıydı.", "label": "positive"},
   {"text": "Ürün defolu çıktı, satıcı ilgilenmedi.", "label": "negative"},
   {"text": "Sitedeki puanlama sistemi çok güvenilir, doğru yönlendirme yapıyor.", "label": "positive"},
   {"text": "Sepetime eklediğim ürün aniden tükenmiş, çok sinir bozucu.", "label": "negative"},
   {"text": "Ürün elime çok hızlı ulaştı, beklediğimden daha iyi bir deneyim oldu.", "label": "positive"},
   {"text": "Ödeme sırasında kart bilgilerimi kabul etmedi, hata verdi.", "label": "negative"},
   {"text": "Mobil uygulama kullanımı çok rahat, alışveriş yapmak keyifli.", "label": "positive"},
   {"text": "Ürünü alırken hediye paketi seçeneği yoktu, keşke ekleseler.", "label": "negative"},
   {"text": "Alışveriş deneyimim harikaydı, tekrar sipariş vereceğim.", "label": "positive"},
   {"text": "Siparişimi verdim ama onaylanmadı, nedenini bilmiyorum.", "label": "negative"},
   {"text": "Ürün tam olarak anlatıldığı gibi geldi, teşekkürler!", "label": "positive"},
   {"text": "Satıcıdan hiçbir şekilde geri dönüş alamıyorum.", "label": "negative"},
   {"text": "Ödeme süreci çok güvenli, hiçbir sorun yaşamadım.", "label": "positive"},
   {"text": "Ürünün fiyatı düştü ama ben daha yüksek fiyata aldım, üzüldüm.", "label": "negative"},
   {"text": "Alışveriş deneyimim çok keyifliydi, tekrar sipariş vereceğim.", "label": "positive"},
   {"text": "İndirim kuponları çalışmıyor, sistem hata veriyor.", "label": "negative"},
   {"text": "Ürün kalitesi çok iyi, beklediğimden daha güzel!", "label": "positive"},
   {"text": "Kargom yanlış şehre gönderilmiş, çok uğraştırdı.", "label": "negative"},
   {"text": "Kredi kartı ile taksit seçenekleri sunmaları çok iyi olmuş.", "label": "positive"},
   {"text": "Müşteri hizmetleri hiç yardımcı olmadı, sürekli geçiştiriyorlar.", "label": "negative"},
   {"text": "Satıcı gerçekten çok ilgili, sorularımı hemen yanıtladı.", "label": "positive"},
   {"text": "Aldığım ürün kusurluydu, değiştirmek için çok zaman harcadım.", "label": "negative"},
   {"text": "Hızlı teslimat, kaliteli ürün ve harika müşteri hizmetleri!", "label": "positive"},
   {"text": "Aldığım ürün tam istediğim gibi, hızlı kargolandı.", "label": "positive"},
    {"text": "Ürün açıklamalarında belirtilen özellikler eksik çıktı.", "label": "negative"},
    {"text": "Fiyat-performans açısından harika bir ürün!", "label": "positive"},
    {"text": "Satıcı sorularıma geç ve yetersiz cevap verdi.", "label": "negative"},
    {"text": "Hediye paketi seçeneği olması çok hoşuma gitti.", "label": "positive"},
    {"text": "Ürün yanlış renkte geldi, iade etmek zorunda kaldım.", "label": "negative"},
    {"text": "Taksit imkanı olması alışverişi çok kolaylaştırıyor.", "label": "positive"},
    {"text": "Siparişim eksik geldi, müşteri hizmetleri ilgilenmedi.", "label": "negative"},
    {"text": "İndirim kodları gerçekten işe yarıyor, güzel fırsatlar var.", "label": "positive"},
    {"text": "Web sitesi çok yavaş, sipariş verirken sürekli hata alıyorum.", "label": "negative"},
    {"text": "Ürünün kalitesi beklentilerimi fazlasıyla karşıladı!", "label": "positive"},
    {"text": "Ürün yanlış kargoya verilmiş, çok uğraşmak zorunda kaldım.", "label": "negative"},
    {"text": "Satıcının hızlı dönüş yapması çok güven verici oldu.", "label": "positive"},
    {"text": "İade süreci çok karışıktı, hala param yatmadı.", "label": "negative"},
    {"text": "Kargom tam zamanında ve sağlam şekilde teslim edildi.", "label": "positive"},
    {"text": "Ürün stokta yokmuş ama sipariş verirken bunu göstermediler.", "label": "negative"},
    {"text": "Alışveriş deneyimim çok keyifliydi, tekrar sipariş vereceğim.", "label": "positive"},
    {"text": "Ürün ambalajı çok kötüydü, zarar görmüştü.", "label": "negative"},
    {"text": "Ödeme seçenekleri çok çeşitli, kolaylık sağlıyor.", "label": "positive"},
    {"text": "Sipariş verirken adres kaydı sürekli hata veriyor.", "label": "negative"},
    {"text": "Ürün kampanyalı fiyatıyla gerçekten çok uygun.", "label": "positive"},
    {"text": "Kargo firmasının hizmeti çok kötüydü, paket ezilmişti.", "label": "negative"},
    {"text": "Sitedeki yorumlar gerçekten yardımcı oldu, ürünü gönül rahatlığıyla aldım.", "label": "positive"},
    {"text": "Aldığım kulaklık bozuk çıktı, değişimle uğraşmak zorunda kaldım.", "label": "negative"},
    {"text": "Mobil uygulama üzerinden alışveriş yapmak çok pratik!", "label": "positive"},
    {"text": "Kargo süresi belirtilenden daha uzun sürdü.", "label": "negative"},
    {"text": "Ürün gerçekten kaliteli ve beklentilerimi aştı.", "label": "positive"},
    {"text": "Ödeme yaparken sistem sürekli hata veriyor, sinir bozucu.", "label": "negative"},
    {"text": "Satıcıdan çok hızlı geri dönüş aldım, müşteri hizmetleri harika.", "label": "positive"},
    {"text": "Aldığım laptop kutusuz ve garanti belgesiz geldi.", "label": "negative"},
    {"text": "İnternette gördüğüm en uygun fiyat buradaydı, süper!", "label": "positive"},
    {"text": "Sipariş numaramı girdim ama kargo takibi yapamıyorum.", "label": "negative"},
    {"text": "Ürün açıklamaları detaylı ve bilgilendirici.", "label": "positive"},
    {"text": "Hediye olarak sipariş verdim ama paketleme özensizdi.", "label": "negative"},
    {"text": "Ücretsiz kargo seçeneği olması alışverişi daha avantajlı hale getiriyor.", "label": "positive"},
    {"text": "Satıcı bana yanlış ürün gönderdi, değişim süreci çok zor oldu.", "label": "negative"},
    {"text": "Hızlı teslimat sayesinde ihtiyacımı hemen karşılayabildim.", "label": "positive"},
    {"text": "Müşteri temsilcisi yardımcı olmuyor, sadece geçiştiriyor.", "label": "negative"},
    {"text": "Ürün beklediğimden daha kaliteli çıktı, tekrar sipariş vereceğim.", "label": "positive"},
    {"text": "Alışveriş sepetim kendiliğinden sıfırlandı, tekrar eklemek zorunda kaldım.", "label": "negative"},
    {"text": "Kargo paketlemesi çok sağlamdı, ürün sorunsuz ulaştı.", "label": "positive"},
    {"text": "Fiyatlar sürekli değişiyor, takip etmek zorlaşıyor.", "label": "negative"},
    {"text": "Web sitesinin arayüzü çok kullanıcı dostu, aradığım ürünü hemen bulabildim.", "label": "positive"},
    {"text": "Aldığım ürün ile fotoğraftaki ürün arasında büyük fark vardı.", "label": "negative"},
    {"text": "Canlı destek hizmetleri çok hızlı ve çözüme yönelik çalışıyor.", "label": "positive"},
    {"text": "İade ettiğim ürün yerine yanlış ürün göndermişler!", "label": "negative"},
    {"text": "Kargo beklediğimden çok daha hızlı geldi, harika bir deneyimdi.", "label": "positive"},
    {"text": "Ürün çok kaliteli, fiyatına göre harika!", "label": "positive"},
   {"text": "Kargom kayboldu, müşteri hizmetleri ilgilenmedi.", "label": "negative"},
   {"text": "Sipariş süreci çok kolaydı, hızlıca tamamladım.", "label": "positive"},
   {"text": "Ürün açıklamada belirtilenden farklı çıktı.", "label": "negative"},
   {"text": "Müşteri desteği harika, hemen yardımcı oldular.", "label": "positive"},
   {"text": "Satıcı sorularımı görmezden geldi, hiç ilgilenmedi.", "label": "negative"},
   {"text": "Kargo çok hızlıydı, beklediğimden önce geldi.", "label": "positive"},
   {"text": "Ödeme sırasında hata aldım, sipariş veremedim.", "label": "negative"},
   {"text": "Fiyatlar piyasaya göre çok uygun, alışveriş yapmak keyifli.", "label": "positive"},
   {"text": "Ürün stokta var görünüyordu ama siparişten sonra iptal edildi.", "label": "negative"},
   {"text": "Paketleme çok özenliydi, ürüne zarar gelmemiş.", "label": "positive"},
   {"text": "İade süreci çok karmaşıktı, paramı geri almak zor oldu.", "label": "negative"},
   {"text": "İndirim döneminde çok avantajlı fiyatlar yakaladım.", "label": "positive"},
   {"text": "Ürün açıklamalarında yanlış bilgi vardı, kandırıldım.", "label": "negative"},
   {"text": "Mobil uygulama çok kullanışlı, rahatça alışveriş yapabiliyorum.", "label": "positive"},
   {"text": "Canlı destek çok yavaş, cevap almak saatler sürdü.", "label": "negative"},
   {"text": "Satıcı çok ilgiliydi, siparişimin durumunu sürekli bildirdi.", "label": "positive"},
   {"text": "Ürün ezilmiş şekilde geldi, iade etmek zorundayım.", "label": "negative"},
   {"text": "Kredi kartı taksit seçeneği olması büyük kolaylık sağladı.", "label": "positive"},
   {"text": "Adres bilgilerim yanlış kaydedilmiş, siparişim yanlış yere gitti.", "label": "negative"},
   {"text": "Kargom çok hızlı geldi, tahminimden önce elime ulaştı.", "label": "positive"},
   {"text": "Müşteri hizmetlerine ulaşmak imkansız, telefonlara bakmıyorlar.", "label": "negative"},
   {"text": "Web sitesi çok kolay kullanılıyor, alışveriş yapmak çok basit.", "label": "positive"},
   {"text": "Ödeme yaptıktan sonra sipariş numarası verilmedi, takip edemiyorum.", "label": "negative"},
   {"text": "Kargo ücreti çok uygundu, başka yerlerde daha pahalıydı.", "label": "positive"},
   {"text": "Kargo firmasının hizmeti kötüydü, teslimat adresimi bulamadılar.", "label": "negative"},
   {"text": "Ürün resimde göründüğünden daha güzel çıktı!", "label": "positive"},
   {"text": "Hediye paketi istemiştim ama ürünü normal kutuyla göndermişler.", "label": "negative"},
   {"text": "Alışveriş deneyimim harikaydı, tekrar buradan alırım.", "label": "positive"},
   {"text": "Sepetime eklediğim ürünler kendiliğinden silindi.", "label": "negative"},
   {"text": "Ücretsiz kargo seçeneği olması alışverişi daha cazip hale getirdi.", "label": "positive"},
   {"text": "Satıcıdan yanlış ürün geldi, iade süreci çok zor.", "label": "negative"},
   {"text": "Kargo tahminimden daha erken geldi, süper!", "label": "positive"},
   {"text": "Ürün elime çok geç ulaştı, çok bekledim.", "label": "negative"},
   {"text": "İade işlemi çok kolaydı, hemen paramı geri aldım.", "label": "positive"},
   {"text": "Kargo takip sistemi çalışmıyor, bilgileri güncellemiyorlar.", "label": "negative"},
   {"text": "Ürün tam istediğim gibi, kesinlikle tekrar sipariş vereceğim.", "label": "positive"},
   {"text": "Ödeme sırasında hata verdi, tekrar denemek zorunda kaldım.", "label": "negative"},
   {"text": "Satıcı çok güvenilir, her soruma hemen yanıt verdi.", "label": "positive"},
   {"text": "Ürün açıklaması yanlış yazılmış, gerçekte farklı çıktı.", "label": "negative"},
   {"text": "Kampanya fiyatları gerçekten çok uygun, harika fırsatlar var.", "label": "positive"},
   {"text": "Müşteri temsilcisi hiç yardımcı olmadı, çözüm sunmadılar.", "label": "negative"},
   {"text": "Alışveriş süreci çok sorunsuzdu, her şey mükemmeldi.", "label": "positive"},
   {"text": "Kargo çok kötüydü, kutu ezilmişti.", "label": "negative"},
   {"text": "Hızlı kargo, kaliteli ürün ve mükemmel müşteri hizmetleri!", "label": "positive"},
   {"text": "Sipariş ettiğim ürün yerine tamamen farklı bir şey göndermişler!", "label": "negative"},
   {"text": "Web sitesindeki arama özelliği çok iyi, aradığımı hemen bulabiliyorum.", "label": "positive"},
   {"text": "Ürün fiyatı sürekli değişiyor, indirim beklerken zam yapıldı.", "label": "negative"},
   {"text": "Kampanya dönemlerinde çok avantajlı fırsatlar oluyor.", "label": "positive"},
   {"text": "Ürün elime ulaşmadan 'teslim edildi' diye gösterildi.", "label": "negative"},
   {"text": "Paketleme çok sağlamdı, ürün sapasağlam ulaştı.", "label": "positive"},
   {"text": "İade için kargo ücretini benim ödemem gerekti, hoşuma gitmedi.", "label": "negative"},
   {"text": "Alışveriş sepeti özelliği çok kullanışlı, sonra almak için ürünleri kaydedebiliyorum.", "label": "positive"},
   {"text": "Müşteri hizmetleri çok geç yanıt veriyor, beklemek zorunda kaldım.", "label": "negative"},
   {"text": "Ürün tam beklediğim gibi geldi, çok memnun kaldım.", "label": "positive"},
   {"text": "Ödeme onaylanmadı, kartımdan para çekildi ama siparişim yok.", "label": "negative"},
   {"text": "Siparişlerim her zaman tam zamanında geliyor, çok memnunum.", "label": "positive"},
   {"text": "Ürün açıklamalarında yanlış bilgi vardı, yanıltıldım.", "label": "negative"},
   {"text": "Paketleme çok özenliydi, hediyelik aldığım ürün çok şık görünüyordu.", "label": "positive"},
   {"text": "Kargo firmasının teslimat süresi çok uzun, beklemeye değmezdi.", "label": "negative"},
   {"text": "Ödeme işlemi çok hızlı ve güvenliydi, hiç sorun yaşamadım.", "label": "positive"},
   {"text": "Müşteri hizmetlerine bağlanmak imkansız, telefonları açmıyorlar.", "label": "negative"},
   {"text": "Satıcı çok ilgiliydi, siparişin her aşamasında bilgilendirdi.", "label": "positive"},
   {"text": "İade süreci çok zor, günlerce uğraştım.", "label": "negative"},
   {"text": "Ürün çok hızlı geldi, teşekkürler!", "label": "positive"},
{"text": "Kargo beklediğimden çok daha geç ulaştı.", "label": "negative"},
{"text": "Müşteri hizmetleri çok ilgili ve yardımcı oldu.", "label": "positive"},
{"text": "Ürün yanlış geldi, iade süreci de karmaşık.", "label": "negative"},
{"text": "Siparişim sorunsuz bir şekilde ulaştı, teşekkürler.", "label": "positive"},
{"text": "Ürün kalitesi beklentilerimin çok altında kaldı.", "label": "negative"},
{"text": "Fiyatlar çok uygun ve kampanyalar harika!", "label": "positive"},
{"text": "Siparişimi iptal etmek istiyorum ama nasıl yapacağımı bulamadım.", "label": "negative"},
{"text": "Ürün açıklamada yazdığı gibi değil, hayal kırıklığına uğradım.", "label": "negative"},
{"text": "Kargo paketlemesi çok özenliydi, teşekkürler.", "label": "positive"},
{"text": "Siparişimde eksik ürün çıktı, çok üzüldüm.", "label": "negative"},
{"text": "Ürün çok kaliteli ve hızlı geldi, memnun kaldım.", "label": "positive"},
{"text": "Müşteri hizmetleri hiç ilgilenmedi, çok kızgınım.", "label": "negative"},
{"text": "Siparişim çok hızlı hazırlandı ve ulaştı, teşekkürler.", "label": "positive"},
{"text": "Ürün kırık geldi, iade süreci de çok zor.", "label": "negative"},
{"text": "Fiyat/performans oranı mükemmel, kesinlikle tavsiye ederim.", "label": "positive"},
{"text": "Siparişimi takip edemiyorum, site çok yavaş çalışıyor.", "label": "negative"},
{"text": "Ürün tam istediğim gibi, çok memnun kaldım.", "label": "positive"},
{"text": "Kargo firması çok kötü, ürün gecikti ve hasarlı geldi.", "label": "negative"},
{"text": "Ürün çok hızlı geldi, paketleme de çok iyiydi.", "label": "positive"},
{"text": "Siparişimde yanlış renk ürün gönderildi, çok üzüldüm.", "label": "negative"},
{"text": "Müşteri hizmetleri çok hızlı ve çözüm odaklı, teşekkürler.", "label": "positive"},
{"text": "Ürün kullanılamayacak durumda geldi, çok kızgınım.", "label": "negative"},
{"text": "Sipariş süreci çok kolay ve hızlıydı, teşekkürler.", "label": "positive"},
{"text": "Ürünün fiyatı çok yüksek, kalitesi ise düşük.", "label": "negative"},
{"text": "Kampanyalar çok cazip, sürekli alışveriş yapıyorum.", "label": "positive"},
{"text": "Siparişim iptal edildi, sebebini de öğrenemedim.", "label": "negative"},
{"text": "Ürün çok kaliteli ve dayanıklı, kesinlikle tavsiye ederim.", "label": "positive"},
{"text": "Kargo takip bilgisi hiç güncellenmedi, ürünü bekliyorum.", "label": "negative"},
{"text": "Ürün çok hızlı geldi ve tam istediğim gibi, teşekkürler.", "label": "positive"},
{"text": "Siparişimde eksik ürün çıktı, çok üzüldüm.", "label": "negative"},
{"text": "Müşteri hizmetleri çok ilgili ve hızlı çözüm sundu.", "label": "positive"},
{"text": "Ürün kırık geldi, iade süreci de çok zor.", "label": "negative"},
{"text": "Fiyatlar çok uygun ve kampanyalar harika!", "label": "positive"},
{"text": "Siparişimi iptal etmek istiyorum ama nasıl yapacağımı bulamadım.", "label": "negative"},
{"text": "Ürün açıklamada yazdığı gibi değil, hayal kırıklığına uğradım.", "label": "negative"},
{"text": "Kargo paketlemesi çok özenliydi, teşekkürler.", "label": "positive"},
{"text": "Siparişimde eksik ürün çıktı, çok üzüldüm.", "label": "negative"},
{"text": "Ürün çok kaliteli ve hızlı geldi, memnun kaldım.", "label": "positive"},
{"text": "Müşteri hizmetleri hiç ilgilenmedi, çok kızgınım.", "label": "negative"},
{"text": "Siparişim çok hızlı hazırlandı ve ulaştı, teşekkürler.", "label": "positive"},
{"text": "Ürün kırık geldi, iade süreci de çok zor.", "label": "negative"},
{"text": "Fiyat/performans oranı mükemmel, kesinlikle tavsiye ederim.", "label": "positive"},
{"text": "Siparişimi takip edemiyorum, site çok yavaş çalışıyor.", "label": "negative"},
{"text": "Ürün tam istediğim gibi, çok memnun kaldım.", "label": "positive"},
{"text": "Kargo firması çok kötü, ürün gecikti ve hasarlı geldi.", "label": "negative"},
{"text": "Ürün çok hızlı geldi, paketleme de çok iyiydi.", "label": "positive"},
{"text": "Siparişimde yanlış renk ürün gönderildi, çok üzüldüm.", "label": "negative"},
{"text": "Müşteri hizmetleri çok hızlı ve çözüm odaklı, teşekkürler.", "label": "positive"},
{"text": "Ürün kullanılamayacak durumda geldi, çok kızgınım.", "label": "negative"},
{"text": "Sipariş süreci çok kolay ve hızlıydı, teşekkürler.", "label": "positive"},
{"text": "Ürünün fiyatı çok yüksek, kalitesi ise düşük.", "label": "negative"},
{"text": "Kampanyalar çok cazip, sürekli alışveriş yapıyorum.", "label": "positive"},
{"text": "Siparişim iptal edildi, sebebini de öğrenemedim.", "label": "negative"},
{"text": "Ürün çok kaliteli ve dayanıklı, kesinlikle tavsiye ederim.", "label": "positive"},
{"text": "Kargo takip bilgisi hiç güncellenmedi, ürünü bekliyorum.", "label": "negative"},
{"text": "Ürün çok hızlı geldi ve tam istediğim gibi, teşekkürler.", "label": "positive"}
]
df = pd.DataFrame(dataset)
#%% metin önişleme ve temizleme; tokenization ve preprossing , train test split
# tokenization
tokenizer = Tokenizer()
tokenizer.fit_on_texts(df["text"])
sequence = tokenizer.texts_to_sequences(df["text"])# her bir sözcüğün sayısallaştırılması !!!
word_index = tokenizer.word_index
# padding processing
maxlen = max(len(seq) for seq in sequence)
X = pad_sequences(sequences=sequence, maxlen=maxlen)

# label encoding
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(df["label"])

# train test ve split
X_train,x_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)
#%% metin temsili ; word_embeding word2vec

sentences = [text.split() for text in df["text"]]
word2vec_model = Word2Vec(sentences, vector_size=100, window = 5, min_count=3)
embeding_dim = 100
embeding_matrix = np.zeros((len(word_index) + 1, embeding_dim))
for word,i in word_index.items():
    if word in word2vec_model.wv:
        embeding_matrix[i] = word2vec_model.wv[word]

#%% building RNN and train 

# build model
model = Sequential()
# embeding
model.add(Embedding(input_dim = len(word_index) + 1, output_dim = embeding_dim, weights = [embeding_matrix], input_length=maxlen,trainable=False))
# RNN layer
model.add(SimpleRNN(50, return_sequences=False))
# outpte
model.add(Dense(1, activation="sigmoid"))
# compile model
model.compile(optimizer="adam", loss = "binary_crossentropy", metrics=["accuracy"])
# train model
model.fit(X_train,Y_train,epochs=50,batch_size=2, validation_data=(x_test,Y_test))
# evaluate rnn model
test_loss, test_accuracy = model.evaluate(x_test, Y_test)
print(f"test loss : {test_loss}, accuracy : {test_accuracy}")
#%% cümle sınıflandırma çalışması

def classify_sentences(sentence):
    seq = tokenizer.texts_to_sequences([sentence])
    padded_seq = pad_sequences(seq, maxlen=maxlen)
    prediction = model.predict(padded_seq)
    predicted_class = (prediction > 0.4).astype(int)
    label = "positive" if predicted_class[0][0] == 1 else "negative"
    return label

sentence = "Siparişimde eksik ürün çıktı, çok üzüldüm"
result = classify_sentences(sentence)
print("result : ", result)